/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.awt.Color;
import javax.swing.JOptionPane;
import water.index;
/**
 *
 * @author Kent
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    Color DefaultColor, ActiveColor;
    
    public Dashboard() {
        initComponents();
        
        DefaultColor = new Color(10,52,66);
        ActiveColor = new Color(217,217,217);
        
        dashboardPanel.setBackground(ActiveColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        logoNamePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ListofCategoriesPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        ListofCategoriesLabel = new javax.swing.JLabel();
        billingsPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        billingsLabel = new javax.swing.JLabel();
        maintenancePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ListofClientsPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ListofClientsLabel = new javax.swing.JLabel();
        monthlyReportsPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        monthlyReportsLabel = new javax.swing.JLabel();
        ListofUsersPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ListofUsersLabel = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        wallPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard | Admin | Water Biling System");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(10, 101, 128));

        sidebarPanel.setBackground(new java.awt.Color(10, 52, 66));

        logoNamePanel.setBackground(new java.awt.Color(10, 52, 66));
        logoNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoNamePanelMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-dash.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 178, 197));
        jLabel3.setText("Water");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 178, 197));
        jLabel5.setText("Billing");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 178, 197));
        jLabel6.setText("System");

        javax.swing.GroupLayout logoNamePanelLayout = new javax.swing.GroupLayout(logoNamePanel);
        logoNamePanel.setLayout(logoNamePanelLayout);
        logoNamePanelLayout.setHorizontalGroup(
            logoNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoNamePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(logoNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        logoNamePanelLayout.setVerticalGroup(
            logoNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoNamePanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(logoNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoNamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        dashboardPanel.setBackground(new java.awt.Color(217, 217, 217));
        dashboardPanel.setName("dashboardPanel"); // NOI18N
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardPanelMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard-icon.png"))); // NOI18N

        dashboardLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(10, 52, 66));
        dashboardLabel.setText("Dashboard");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashboardLabel))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        mainPanel.setBackground(new java.awt.Color(9, 33, 43));

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(217, 217, 217));
        jLabel9.setText("Main");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListofCategoriesPanel.setBackground(new java.awt.Color(10, 52, 66));
        ListofCategoriesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListofCategoriesPanelMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listofcat.png"))); // NOI18N
        jLabel17.setText("jLabel10");

        ListofCategoriesLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ListofCategoriesLabel.setForeground(new java.awt.Color(217, 217, 217));
        ListofCategoriesLabel.setText("List of Categories");

        javax.swing.GroupLayout ListofCategoriesPanelLayout = new javax.swing.GroupLayout(ListofCategoriesPanel);
        ListofCategoriesPanel.setLayout(ListofCategoriesPanelLayout);
        ListofCategoriesPanelLayout.setHorizontalGroup(
            ListofCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListofCategoriesPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListofCategoriesLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ListofCategoriesPanelLayout.setVerticalGroup(
            ListofCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListofCategoriesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListofCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListofCategoriesLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        billingsPanel.setBackground(new java.awt.Color(10, 52, 66));
        billingsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billingsPanelMousePressed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billings_icon.png"))); // NOI18N
        jLabel12.setText("jLabel10");

        billingsLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        billingsLabel.setForeground(new java.awt.Color(217, 217, 217));
        billingsLabel.setText("Billings");

        javax.swing.GroupLayout billingsPanelLayout = new javax.swing.GroupLayout(billingsPanel);
        billingsPanel.setLayout(billingsPanelLayout);
        billingsPanelLayout.setHorizontalGroup(
            billingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(billingsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        billingsPanelLayout.setVerticalGroup(
            billingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(billingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billingsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        maintenancePanel.setBackground(new java.awt.Color(9, 33, 43));

        jLabel16.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(217, 217, 217));
        jLabel16.setText("Maintenance");

        javax.swing.GroupLayout maintenancePanelLayout = new javax.swing.GroupLayout(maintenancePanel);
        maintenancePanel.setLayout(maintenancePanelLayout);
        maintenancePanelLayout.setHorizontalGroup(
            maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenancePanelLayout.setVerticalGroup(
            maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListofClientsPanel.setBackground(new java.awt.Color(10, 52, 66));
        ListofClientsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListofClientsPanelMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listofclients_color.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        ListofClientsLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ListofClientsLabel.setForeground(new java.awt.Color(217, 217, 217));
        ListofClientsLabel.setText("List of Clients");

        javax.swing.GroupLayout ListofClientsPanelLayout = new javax.swing.GroupLayout(ListofClientsPanel);
        ListofClientsPanel.setLayout(ListofClientsPanelLayout);
        ListofClientsPanelLayout.setHorizontalGroup(
            ListofClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListofClientsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListofClientsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListofClientsPanelLayout.setVerticalGroup(
            ListofClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListofClientsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListofClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListofClientsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        monthlyReportsPanel.setBackground(new java.awt.Color(10, 52, 66));
        monthlyReportsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthlyReportsPanelMousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monthlyrep.png"))); // NOI18N
        jLabel19.setText("jLabel10");

        monthlyReportsLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        monthlyReportsLabel.setForeground(new java.awt.Color(217, 217, 217));
        monthlyReportsLabel.setText("Monthly Reports");

        javax.swing.GroupLayout monthlyReportsPanelLayout = new javax.swing.GroupLayout(monthlyReportsPanel);
        monthlyReportsPanel.setLayout(monthlyReportsPanelLayout);
        monthlyReportsPanelLayout.setHorizontalGroup(
            monthlyReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlyReportsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(monthlyReportsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monthlyReportsPanelLayout.setVerticalGroup(
            monthlyReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthlyReportsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(monthlyReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(monthlyReportsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        ListofUsersPanel.setBackground(new java.awt.Color(10, 52, 66));
        ListofUsersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListofUsersPanelMousePressed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listuser pale.png"))); // NOI18N
        jLabel21.setText("jLabel10");

        ListofUsersLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ListofUsersLabel.setForeground(new java.awt.Color(217, 217, 217));
        ListofUsersLabel.setText("List of Users");

        javax.swing.GroupLayout ListofUsersPanelLayout = new javax.swing.GroupLayout(ListofUsersPanel);
        ListofUsersPanel.setLayout(ListofUsersPanelLayout);
        ListofUsersPanelLayout.setHorizontalGroup(
            ListofUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListofUsersPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListofUsersLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListofUsersPanelLayout.setVerticalGroup(
            ListofUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListofUsersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListofUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListofUsersLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        settingsPanel.setBackground(new java.awt.Color(10, 52, 66));
        settingsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsPanelMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings pale.png"))); // NOI18N
        jLabel23.setText("jLabel10");

        settingsLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(217, 217, 217));
        settingsLabel.setText("Settings");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(settingsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(maintenancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(logoNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(settingsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListofUsersPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyReportsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billingsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListofClientsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListofCategoriesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(logoNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListofClientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(billingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthlyReportsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maintenancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListofCategoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListofUsersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("MANAGEMENT SITE - Admin");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(10, 52, 66));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(217, 217, 217));
        jButton1.setText("Logout");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wallPanelLayout = new javax.swing.GroupLayout(wallPanel);
        wallPanel.setLayout(wallPanelLayout);
        wallPanelLayout.setHorizontalGroup(
            wallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1137, Short.MAX_VALUE)
        );
        wallPanelLayout.setVerticalGroup(
            wallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wallPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wallPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?","Confirm...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
            new index().setVisible(true);
            this.setVisible(false);
        }
        else if(response == JOptionPane.NO_OPTION) {
            this.setVisible(true);
        }
        else if(response == JOptionPane.CLOSED_OPTION){
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoNamePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoNamePanelMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_logoNamePanelMouseClicked

    private void ListofClientsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListofClientsPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(DefaultColor);
        ListofClientsPanel.setBackground(ActiveColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(DefaultColor);
        
        dashboardLabel.setForeground(ActiveColor);
        ListofClientsLabel.setForeground(DefaultColor);
        billingsLabel.setForeground(ActiveColor);
        monthlyReportsLabel.setForeground(ActiveColor);
        ListofCategoriesLabel.setForeground(ActiveColor);
        ListofUsersLabel.setForeground(ActiveColor);
        settingsLabel.setBackground(ActiveColor);
        
    }//GEN-LAST:event_ListofClientsPanelMousePressed

    private void billingsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingsPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(DefaultColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(ActiveColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(DefaultColor);
        
        dashboardLabel.setForeground(ActiveColor);
        ListofClientsLabel.setForeground(ActiveColor);
        billingsLabel.setForeground(DefaultColor);
        monthlyReportsLabel.setForeground(ActiveColor);
        ListofCategoriesLabel.setForeground(ActiveColor);
        ListofUsersLabel.setForeground(ActiveColor);
        settingsLabel.setBackground(ActiveColor);
    }//GEN-LAST:event_billingsPanelMousePressed

    private void dashboardPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(ActiveColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(DefaultColor);
        
        dashboardLabel.setForeground(DefaultColor);
        ListofClientsLabel.setForeground(ActiveColor);
        billingsLabel.setForeground(ActiveColor);
        monthlyReportsLabel.setForeground(ActiveColor);
        ListofCategoriesLabel.setForeground(ActiveColor);
        ListofUsersLabel.setForeground(ActiveColor);
        settingsLabel.setBackground(ActiveColor);
    }//GEN-LAST:event_dashboardPanelMousePressed

    private void monthlyReportsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthlyReportsPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(DefaultColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(ActiveColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(DefaultColor);
        
        dashboardLabel.setForeground(ActiveColor);
        ListofClientsLabel.setForeground(ActiveColor);
        billingsLabel.setForeground(ActiveColor);
        monthlyReportsLabel.setForeground(DefaultColor);
        ListofCategoriesLabel.setForeground(ActiveColor);
        ListofUsersLabel.setForeground(ActiveColor);
        settingsLabel.setBackground(ActiveColor);
    }//GEN-LAST:event_monthlyReportsPanelMousePressed

    private void ListofCategoriesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListofCategoriesPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(DefaultColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(ActiveColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(DefaultColor);
        
        dashboardLabel.setForeground(ActiveColor);
        ListofClientsLabel.setForeground(ActiveColor);
        billingsLabel.setForeground(ActiveColor);
        monthlyReportsLabel.setForeground(ActiveColor);
        ListofCategoriesLabel.setForeground(DefaultColor);
        ListofUsersLabel.setForeground(ActiveColor);
        settingsLabel.setBackground(ActiveColor);
    }//GEN-LAST:event_ListofCategoriesPanelMousePressed

    private void ListofUsersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListofUsersPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(DefaultColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(ActiveColor);
        settingsPanel.setBackground(DefaultColor);
        
        dashboardLabel.setForeground(ActiveColor);
        ListofClientsLabel.setForeground(ActiveColor);
        billingsLabel.setForeground(ActiveColor);
        monthlyReportsLabel.setForeground(ActiveColor);
        ListofCategoriesLabel.setForeground(ActiveColor);
        ListofUsersLabel.setForeground(DefaultColor);
        settingsLabel.setBackground(ActiveColor);
    }//GEN-LAST:event_ListofUsersPanelMousePressed

    private void settingsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelMousePressed
        // TODO add your handling code here:
        dashboardPanel.setBackground(DefaultColor);
        ListofClientsPanel.setBackground(DefaultColor);
        billingsPanel.setBackground(DefaultColor);
        monthlyReportsPanel.setBackground(DefaultColor);
        ListofCategoriesPanel.setBackground(DefaultColor);
        ListofUsersPanel.setBackground(DefaultColor);
        settingsPanel.setBackground(ActiveColor);
        
        dashboardLabel.setForeground(ActiveColor);
        ListofClientsLabel.setForeground(ActiveColor);
        billingsLabel.setForeground(ActiveColor);
        monthlyReportsLabel.setForeground(ActiveColor);
        ListofCategoriesLabel.setForeground(ActiveColor);
        ListofUsersLabel.setForeground(ActiveColor);
        settingsLabel.setBackground(DefaultColor);
    }//GEN-LAST:event_settingsPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListofCategoriesLabel;
    private javax.swing.JPanel ListofCategoriesPanel;
    private javax.swing.JLabel ListofClientsLabel;
    private javax.swing.JPanel ListofClientsPanel;
    private javax.swing.JLabel ListofUsersLabel;
    private javax.swing.JPanel ListofUsersPanel;
    private javax.swing.JLabel billingsLabel;
    private javax.swing.JPanel billingsPanel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel logoNamePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel maintenancePanel;
    private javax.swing.JLabel monthlyReportsLabel;
    private javax.swing.JPanel monthlyReportsPanel;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel wallPanel;
    // End of variables declaration//GEN-END:variables
}
